# Tensors

* Tensors are a specialized data stucture that is very similar to arrays and matrices.

* In Pytorch, we use tensors to encode the inputs and outputs of a model as well as parameters.

* Tensors are similar to array and matrices except that tensors can run on GPUs or, the other hardware accelerators. In fact, tensors and numpy arrays can share the same underlying memory, eliminating the need to copy data.


In [1]:
import numpy as np
import torch


## Initializing tensors

### 1. From data

In [2]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


### 2. From numpy array 


In [3]:
x_array = np.array(data)
x_tensor = torch.from_numpy(x_array)
print(x_tensor)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


### 3. From another tensor

In [4]:
x_ones = torch.ones_like(x_data) #retains the properties of tensor initiale
print(x_ones)
print(x_ones.dtype)

tensor([[1, 1],
        [1, 1]])
torch.int64


In [5]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand.dtype)


torch.float32


### 4. With random or constant values

In [6]:
shape =(2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(ones_tensor)
print(rand_tensor)
print(zeros_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.6557, 0.0932, 0.4438],
        [0.9049, 0.5850, 0.1955]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Attributes of tensors  

In [7]:
print(ones_tensor.dtype)
print(ones_tensor.device)
print(ones_tensor.shape)

torch.float32
cpu
torch.Size([2, 3])


## Operations on tensors

### 1. move tensor to the GPU


In [8]:
if(torch.cuda.is_available()):
    ones_tensor = ones_tensor.to('cuda')
    

In [9]:
print(ones_tensor.device)

cuda:0


### 2. Standard indexing and slicing

In [10]:
tensor = torch.ones(4,4)

print('First row: ', tensor[0] )
print('First column: ', tensor[:, 0])
print('Last column: ',tensor [:,-1])

tensor[:,-1] = 0

print(tensor)


First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column:  tensor([1., 1., 1., 1.])
tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])


### 3. Joining tensors

We can use torch.cat to concatenate a sequence of tensors along a given dimension. 

In [11]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.]])


In [14]:
t1 = torch.cat([tensor, tensor, tensor], dim=0)
print(t1)

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])


### 4. Arithmetic operation

In [15]:
# Matrix multiplication between two tensors.
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3= torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [16]:
# Element-wise product.

z1 = tensor.mul(tensor)
z2 = tensor * tensor

z3= torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)


tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])

### 5. Single-element tensors

In [17]:
agg = tensor.sum()
print(agg)

agg_item = agg.item()
print(agg_item)

tensor(12.)
12.0


### 6. Inplace operation

In [18]:
print(tensor)
tensor.add_(5)
print(tensor)

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])
tensor([[6., 6., 6., 5.],
        [6., 6., 6., 5.],
        [6., 6., 6., 5.],
        [6., 6., 6., 5.]])


### 7. Bridge with Numpy


Tensors on CPU and numpy array can share their underlying memory locations, and changing one will change the other


In [28]:
t = torch.ones(5)
n = t.numpy()
print(t)
print(n)
print("\n")

t.add_(5)
print(t)
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


tensor([6., 6., 6., 6., 6.])
[6. 6. 6. 6. 6.]


In [26]:
# Numpy to tensor
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 5, out=n)
print(n)
print(t)

[6. 6. 6. 6. 6.]
tensor([6., 6., 6., 6., 6.], dtype=torch.float64)
